# Generated by Django 4.1.2 on 2022-12-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iycee', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='userAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
