# Generated by Django 4.1.2 on 2022-12-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iycee', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pic'),
        ),
    ]
