# Generated by Django 4.1.2 on 2022-12-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iycee', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=b'I01\n', max_length=254, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=b'I01\n', max_length=150, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=b'I01\n', default='default.png', null=b'I01\n', upload_to='profile_pic'),
        ),
    ]
