# Generated by Django 4.1.2 on 2022-12-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iycee', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=b'I01\n', default='default.png', null=b'I01\n', upload_to='profile_pic'),
        ),
    ]
