# Generated by Django 4.1.2 on 2022-12-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iycee', '0010_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
