# Generated by Django 4.1.2 on 2022-12-25 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iycee', '0011_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=b'I01\n', max_length=150, null=b'I01\n')),
                ('email', models.EmailField(blank=b'I01\n', max_length=254, null=b'I01\n')),
                ('phone', models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n')),
                ('image', models.ImageField(blank=b'I01\n', default='default.png', null=b'I01\n', upload_to='profile_pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
