# Generated by Django 4.1.2 on 2023-01-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iycee', '0013_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='description',
            field=models.TextField(blank=b'I01\n', null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=b'I01\n', null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
